# Generated by Django 3.1.7 on 2021-04-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210407_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_world',
            new_name='fees_in_world',
        ),
    ]
